# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *.yaml,
  # and age is used
  # - path_regex: .yaml$

  ## This key is the public key of the age key pair
  - age: "age1zs3q2vfmr4vy4zw2h5tysnrs73rvmaf6xxx9wut6v0ft0sya9d8qsw2d6f"
