apiVersion: v1
data:
    SECRET1: ENC[AES256_GCM,data:YaQ9SOFA1wA=,iv:AylC28LEWF+3GIj+rKks5LRF6vkgRtS+Awxqlvn6HnQ=,tag:rux1U7JzRCQGhch991KNFw==,type:str]
    SECRET2: ENC[AES256_GCM,data:UZly9/dtNiBUjgO9CCU=,iv:3t/igC63vvj3Q+HviXqDfhDJIi6fklv6nULbYLitnjU=,tag:snwX70zazS1vKuEKYJFI5w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-aghe-secret-example
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs3q2vfmr4vy4zw2h5tysnrs73rvmaf6xxx9wut6v0ft0sya9d8qsw2d6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OEhZQmVTdWdrdG5NdDdj
            a2wwUVBrZWNTZkJIdUxYaHQzU0xvQU51VEdRCjRLalVKaVhRd2R0eXl0UG9SUXlZ
            UzBSWFhDZUJTWkVlRCtnS0thTW1kQ3MKLS0tIEQvUXVBYTZOa1k4K3VLaFkyTm9p
            bkxZUjQvUFdtcWxXdlFnUU5VVVFvd3cKDMzZfZRqnNC6EfObo2TfgMa4NFEg8m/A
            Tdjx16Rh4EkXD9z/gB+H8CQR7cKiMy/f7zvZ/A+XjthlGx0LfU5VhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T23:49:44Z"
    mac: ENC[AES256_GCM,data:XeYPib3rb3rJVy42GMlGw6Z/0LsoIifgt6mcGBT2wYoqAHO+VJxxBx4Fbts4G7XOyxkA2WWSW4CCP3qNyt6wkX6mvkWCh+LkHdho4ZkVhbgElqYDaKcl8YfHBzUs2QwrzHDVmWEXFY01uf+jTcsutDaKKznGgaH1+KedtyFsUjE=,iv:sdAXvt3DN1EWw1cT3l2sUhQsDjjSmGn+a9cjb98za08=,tag:yvzAnvsMejqfKBeZNWt3rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
