---
- name: localhost

  # No inventory file, could also be 127.0.0.1
  hosts: localhost

  ## Important! These are crucial for the playbook to work
  vars:
    ansible_connection: local
    ansible_python: "{{ ansible_playbook_python }}"

  ## Make sure homebrew is up to date
  pre_tasks:
    - name: update homebrew
      ansible.builtin.homebrew:
        upgrade_all: yes
      changed_when: false

  tasks:
    - include_tasks: tasks/hostname.yaml
    - include_tasks: tasks/users.yaml
