#!/usr/bin/env -S just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-filename := '.env'
set dotenv-load := true
# set dotenv-path := './'
set ignore-comments := false
log := "warn"

set export
# export DOCKER_BUILDKIT=1

# Run the build command
build:
    @echo "Building..."
    docker build --secret id=secrets,src=$(pwd)/.secrets -t docker-secret .

ssh:
    @echo "Building..."
    docker build --ssh default -t docker-secret .

# Run the test command
history:
    @echo "History..."
    docker history docker-secret
