version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - dev-container:python3.10-slim
    container_name: dev-container_python
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - ./app:/app